spring.datasource.url=jdbc:mysql://localhost:3306/dinewise
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Places
google.places.api.key=AIzaSyAGIu8uEtOLAWwnpncwW2AO1EsF-iA3pZ4

# SerpAPI
serp.api.key=9030d573d42c8311711d490ae7f13a329cbac27070c96fa54e32a8b4e644cdba